"""
Prompt Builder
Constructs final prompt by inserting trigger words from selected LoRAs.
"""
from typing import List, Dict, Any, Set


def collect_trigger_words(loras: List[Dict[str, Any]]) -> List[str]:
    """
    Collect all trigger words from selected LoRAs.
    
    Args:
        loras: List of LoRA catalog entries
        
    Returns:
        List of unique trigger words
    """
    triggers = []
    seen = set()
    
    for lora in loras:
        lora_triggers = lora.get('trained_words', [])
        for trigger in lora_triggers:
            trigger = trigger.strip()
            if trigger and trigger not in seen:
                seen.add(trigger)
                triggers.append(trigger)
    
    return triggers


def build_final_prompt(
    base_context: str,
    selected_loras: List[Dict[str, Any]],
    insert_position: str = 'start',
    separator: str = ', '
) -> str:
    """
    Build final prompt by inserting trigger words.
    
    Args:
        base_context: User's base context/prompt
        selected_loras: List of selected LoRA catalog entries
        insert_position: Where to insert triggers ('start', 'end', or 'none')
        separator: Separator between triggers
        
    Returns:
        Final prompt string
    """
    # Collect trigger words
    triggers = collect_trigger_words(selected_loras)
    
    if not triggers or insert_position == 'none':
        return base_context.strip()
    
    # Join triggers
    trigger_text = separator.join(triggers)
    
    # Insert based on position
    if insert_position == 'start':
        if base_context.strip():
            return f"{trigger_text}{separator}{base_context.strip()}"
        else:
            return trigger_text
    
    elif insert_position == 'end':
        if base_context.strip():
            return f"{base_context.strip()}{separator}{trigger_text}"
        else:
            return trigger_text
    
    else:
        return base_context.strip()


def build_prompt_from_llm_output(
    llm_prompt: str,
    ensure_triggers: List[str] = None
) -> str:
    """
    Build prompt from LLM output, optionally ensuring certain triggers are present.
    
    Args:
        llm_prompt: Prompt generated by LLM
        ensure_triggers: Optional list of triggers that must be present
        
    Returns:
        Final prompt with triggers ensured
    """
    prompt = llm_prompt.strip()
    
    if not ensure_triggers:
        return prompt
    
    # Check which triggers are missing
    prompt_lower = prompt.lower()
    missing_triggers = []
    
    for trigger in ensure_triggers:
        trigger_lower = trigger.lower()
        if trigger_lower not in prompt_lower:
            missing_triggers.append(trigger)
    
    # Add missing triggers to the start
    if missing_triggers:
        trigger_text = ', '.join(missing_triggers)
        prompt = f"{trigger_text}, {prompt}"
    
    return prompt
